module7 : new lesson
e-vinci/web3 pull request #6
Opened 2024-10-17 16:21 UTC by e-baron

Module7 : React Router and Antd ready for 2024

2024-10-22 14:40 UTC, lbrucher requested changes

2024-10-22 14:40 UTC, lbrucher commented on src/mdx-pages/modules/7.fr.mdx
> +Ainsi, dans une **SPA**, une seule page est chargée la toute première fois que l'on accède au serveur : c'est `index.html` et tous les assets associés (scripts JS, les images, CSS, sons...). Par la s
Une autre manière d'expliquer la chose, sans aucune obligation ;-)

Dans les applications "old school" de type **Multi-Page-Application** (**MPA**), chaque click de la souris génère un HTTP GET vers le serveur qui renvoie l'entièreté de la page HTML, même si seulement une petite partie doit être modifiée. Par exemple, un click pour afficher ou cacher un élément de la page va initier un HTTP GET vers le serveur qui renverra une nouvelle page entière, avec l'élément maintenant affiché ou caché.

Dans les applications que nous développons dans ce cours, l'architecture est complètement différente. Nous développons des **Single-Page-Applications** (**SPA**) où seulement des parties de page sont modifiées en réponse à une action de l'utilisateur. Donc on charge une page principale lors du premier accès à l'application et ensuite seulement des parties de cette page se voient modifiées en fonction des actions de l'utilisateur (d'où le nom `Single Page App`).

Le routage est le principe d'associer un URL à une modification de page (en SPA) ou à une navigation vers une autre page (en MPA).

Ainsi, dans une **SPA**, une seule page est chargée la toute première fois que l'on accède au serveur : c'est `index.html` et tous les assets associés (scripts JS, les images, CSS, sons...). 
Ensuite, les différentes parties de l'application qui peuvent être affichées sont associées à un URL qui sera décrit dans la configuration du router de l'application React. L'affichage de ces parties (composants) se fera via une navigation par hyperlink, typiquement via un `<a>`. Le browser se charge alors de modifier le DOM (càd le rendu de toute la page web) généralement en remplaçant des éléments du DOM par le composant React associé à la nouvelle route.

2024-10-22 14:40 UTC, lbrucher commented on src/mdx-pages/modules/7.fr.mdx
> +A notre stade actuel de connaissances, nous pourrions très facilement organiser la navigation entre plusieurs page, simplement à l'aide d'une variable d'état et des gestionnaires de clics.
typo: ... la navigation entre plusieurs page**s** ...

2024-10-22 14:40 UTC, lbrucher commented on src/mdx-pages/modules/7.fr.mdx
> +export { HomePage, AboutPage, ContactPage };
cet export n'est pas nécessaire à ce stade... supprimer peut-être?

2024-10-22 14:40 UTC, lbrucher commented on src/mdx-pages/modules/7.fr.mdx
> +Si l'on souhaite se rapprocher du design initial, nous pouvons utiliser le hook `useNavigation` qui offre une fonction pour naviguer vers une nouvelle route.
`useNavigation` -> `useNavigate`

2024-10-22 14:40 UTC, lbrucher commented on src/mdx-pages/modules/7.fr.mdx
> +Parfois, il est intéressant qu'une même composant soit appelé sur toute une famille de routes.
Typo: ... qu'un même composant ...

2024-10-22 14:40 UTC, lbrucher commented on src/mdx-pages/modules/7.fr.mdx
> +Pour la pizzeria, l'IHM que nous avons développée s'est terminée avec le code du tutoriel `ui-library`. Néanmoins, pour la suite du cours, nous ne souhaitons pas vous imposer d'utiliser des composant
Tu me perd là... Pizzeria? `ui-library`?

2024-10-22 14:40 UTC, lbrucher commented on src/mdx-pages/modules/7.fr.mdx
> +Si nécessaire, vous pouvez trouver le code associé à ce tutoriel ici : [router-starter](https://github.com/e-vinci/ts-demos/tree/main/front/routing).
renommer `router-starter` en `router` et renommer le répertoire `routing` en `router` dans `web3-exercises/tutorials`

2024-10-22 14:40 UTC, lbrucher commented on src/mdx-pages/modules/7.fr.mdx
> +Nous avons maintenant utilisé nos premiers composants "externes" proposés par **Ant Design**. Nous allons maintenant remplacer notre balise **`form`* par le formulaire **Ant Design** qui va nous rend
`**`form`*` -> `**`form`**`

2024-10-24 13:36 UTC, e-baron commented on src/mdx-pages/modules/7.fr.mdx
> +Pour la pizzeria, l'IHM que nous avons développée s'est terminée avec le code du tutoriel `ui-library`. Néanmoins, pour la suite du cours, nous ne souhaitons pas vous imposer d'utiliser des composant
En effet, j'ai corrigé.

2024-10-24 13:38 UTC, merged